name: Continuos Integration

#Quando o workflow é executado
on:
  push:
    branches: [ "main" ] #Executa quando há push na branch "main"
  pull_request:
    branches: [ "main" ] #Executa também quando há PR aberta para "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #Sistema operacional usado no Actions

    strategy:
      matrix:
        node-version: [20.x] #Versao node

    steps:
      #Faz checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      #Configura o Node.js e cache do npm
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      #Instala as dependências
      - name: Install dependencies
        run: npm install

      #Executa o build do projeto
      - name: Build project
        run: npm run build

      #Dispara o deploy no Vercel via webhook
      - name: Trigger Vercel Deployment
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST "$VERCEL_DEPLOY_HOOK_URL"
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
